######################################################################
# Automatically generated by qmake (2.01a) pe 1. heinä 18:58:41 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . GeneratedFiles
INCLUDEPATH += .

# Input
HEADERS += wc3mousecapture.h
SOURCES += main.cpp wc3mousecapture.cpp
RESOURCES += wc3mousecapture.qrc
